server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer

eureka:
  client:
    # 表示是否将当前服务注册进注册中心，默认为true
    register-with-eureka: true
    # 是否从注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群一定要为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 实例名称
    instance-id: order80
    # 访问路径显示IP地址
    prefer-ip-address: true