server:
  port: 8001

spring:
  application:
    name: cloud-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password

eureka:
  client:
    # 表示是否将当前服务注册进注册中心，默认为true
    register-with-eureka: true
    # 是否从注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群一定要为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 实例名称
    instance-id: payment8001
    # 访问路径显示IP地址
    prefer-ip-address: true
    # EurekaClient向服务端发送心跳的时间间隔，默认为30秒，单位为秒
    lease-renewal-interval-in-seconds: 20
    # Eureka服务端在收到最后一次心跳后的等待时间上限，超时就剔除，默认为90秒，单位为秒
    lease-expiration-duration-in-seconds: 50
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yww.springcloud.entity
