server:
  port: 80
spring:
  application:
    name: feign-payment-consumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
feign:
  client:
    config:
      default:
        # 建立连接后从服务器读取到可用资源所用的时间
        connectTimeout: 5000
        # 建立连接建立所用时间
        readTimeout: 5000
logging:
  level:
    com.yww.springcloud.service.PaymentFeignService: debug

